# Generated by Django 3.1.3 on 2020-11-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('wo_ho_so_do', models.CharField(max_length=255)),
                ('home_address', models.CharField(max_length=512)),
                ('mobile_number_1', models.CharField(max_length=10)),
                ('mobile_number_2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('home_address', models.CharField(max_length=512)),
                ('mobile_number_1', models.CharField(max_length=10)),
                ('mobile_number_2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('to lose weight', 'to lose weight'), ('to reduce stress', 'to reduce stress'), ('to improve cardiovascular', 'to improve cardiovascular')], max_length=255)),
                ('other_goals', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.member')),
            ],
        ),
    ]
