# Generated by Django 3.1.3 on 2020-11-21 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.trainer'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='other_goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
