# Generated by Django 3.1.3 on 2020-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20201121_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
