# Generated by Django 3.1.3 on 2020-11-21 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_member_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memberships.member')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('tuberculosis', 'tuberculosis'), ('diabetes', 'diabetes'), ('bronchitis asthama', 'bronchitis asthama')], max_length=255)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2020)])),
                ('medical_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.medicalprofile')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.member')),
            ],
        ),
    ]
