# Generated by Django 3.1.3 on 2020-11-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20201121_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='medical_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.medicalprofile'),
        ),
    ]
