# Generated by Django 3.1.3 on 2020-11-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_auto_20201121_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='memberships.member'),
        ),
    ]
