# Generated by Django 3.1.3 on 2020-11-21 14:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_auto_20201121_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='addiction_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='chronic_ear_disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='family_disease_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='hospitalized_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='prolonged_drug_intake_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='surgery_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='thyroid_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='SystemicExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.TextField(blank=True, null=True)),
                ('cvs', models.TextField(blank=True, null=True)),
                ('git', models.TextField(blank=True, null=True)),
                ('rs', models.TextField(blank=True, null=True)),
                ('ent', models.TextField(blank=True, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.member')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pulse', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('weight', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('chest_unexpanded', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('chest_expanded', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('others', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.member')),
            ],
        ),
    ]
