# Generated by Django 3.1.3 on 2020-11-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0011_auto_20201121_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('yearly', 'yearly'), ('half yearly', 'half yearly'), ('monthly', 'monthly')], max_length=255)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('next_due_date', models.DateField(blank=True)),
                ('amount_paid', models.PositiveBigIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.member')),
            ],
        ),
    ]
