# Generated by Django 3.1.3 on 2020-11-21 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0013_auto_20201121_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
