# Generated by Django 3.1.3 on 2020-11-21 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0014_auto_20201121_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2020)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.CharField(choices=[('to lose weight', 'to lose weight'), ('to reduce stress', 'to reduce stress'), ('to improve cardiovascular', 'to improve cardiovascular')], default='to lose weight', max_length=255),
            preserve_default=False,
        ),
    ]
