# Generated by Django 3.1.3 on 2020-11-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0015_auto_20201121_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=20),
            preserve_default=False,
        ),
    ]
