# Generated by Django 3.1.3 on 2020-11-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0016_fee_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
