# Generated by Django 3.1.3 on 2020-11-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0017_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='memberships.member'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='memberships.member'),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_examination', to='memberships.member'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='memberships.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='memberships.trainer'),
        ),
        migrations.AlterField(
            model_name='systemicexamination',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemic_examination', to='memberships.member'),
        ),
    ]
