# Generated by Django 3.1.3 on 2020-11-22 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0019_goal_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalexamination',
            name='date_of_examination',
            field=models.DateField(default=datetime.date(2020, 11, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemicexamination',
            name='date_of_examination',
            field=models.DateField(default=datetime.date(2020, 11, 22)),
            preserve_default=False,
        ),
    ]
