# Generated by Django 3.1.3 on 2020-11-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0020_auto_20201122_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date_of_payment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
