# Generated by Django 3.1.3 on 2020-11-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0021_auto_20201123_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
