# Generated by Django 3.1.3 on 2020-11-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0022_trainer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_number_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='mobile_number_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='disease',
            unique_together={('member', 'disease')},
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('member', 'goal')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('first_name', 'last_name', 'dob', 'mobile_number_1')},
        ),
        migrations.AlterUniqueTogether(
            name='trainer',
            unique_together={('first_name', 'last_name', 'dob', 'mobile_number_1')},
        ),
    ]
