# Generated by Django 3.1.3 on 2020-11-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0023_auto_20201124_0512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('first_name', 'last_name', 'mobile_number_1')},
        ),
        migrations.AlterUniqueTogether(
            name='trainer',
            unique_together={('first_name', 'last_name', 'mobile_number_1')},
        ),
    ]
