# Generated by Django 3.1.3 on 2020-11-27 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0026_auto_20201124_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='fee',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
