# Generated by Django 3.1.3 on 2020-11-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0026_auto_20201124_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='initial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_type',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Half Yearly', 'Half Yearly'), ('Monthly', 'Monthly')], max_length=255),
        ),
    ]
