# Generated by Django 3.1.3 on 2020-11-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0028_member_membership_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemicexamination',
            name='cns',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemicexamination',
            name='cvs',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemicexamination',
            name='ent',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemicexamination',
            name='git',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemicexamination',
            name='others',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemicexamination',
            name='rs',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=10),
        ),
    ]
