# Generated by Django 3.1.3 on 2020-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0029_auto_20201128_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='addiction_history',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='chronic_ear_disease',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='family_disease_history',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='hospitalized_history',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='prolonged_drug_intake_history',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='surgery_history',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='thyroid_history',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='systemicexamination',
            name='others',
            field=models.TextField(blank=True, default='Normal', null=True),
        ),
    ]
