# Generated by Django 3.1.3 on 2020-12-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0030_auto_20201128_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease',
            field=models.CharField(choices=[('Tuberculosis', 'Tuberculosis'), ('Diabetes', 'Diabetes'), ('Bronchitis Asthama', 'Bronchitis Asthama'), ('Hypertension', 'Hypertension'), ('Fits', 'Fits'), ('Jaundice', 'Jaundice'), ('Rheumatic Fever/Gouts/Arthritis/Lower Back Ache/PIVD', 'Rheumatic Fever/Gouts/Arthritis/Lower Back Ache/PIVD'), ('Any Kind Of Heart Disease', 'Any Kind Of Heart Disease'), ('Fainting Attacks', 'Fainting Attacks'), ('Skin Disease', 'Skin Disease'), ('Venereal Disease/ HIV', 'Venereal Disease/ HIV'), ('Kidney Disease', 'Kidney Disease'), ('Nervous Breakdown/Depression', 'Nervous Breakdown/Depression'), ('Fever For Prolonged Duration', 'Fever For Prolonged Duration'), ('Diarrhea For Prolonged Duration', 'Diarrhea For Prolonged Duration'), ('Glaucoma/Eye Disease/Color Blindness', 'Glaucoma/Eye Disease/Color Blindness')], max_length=255),
        ),
    ]
