# Generated by Django 3.1.3 on 2020-12-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0031_auto_20201201_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.CharField(choices=[('To Lose Weight', 'To Lose Weight'), ('To Reduce Stress', 'To Reduce Stress'), ('To Improve Cardiovascular', 'To Improve Cardiovascular'), ('To Increase Self-Esteem', 'To Increase Self-Esteem'), ('To Improve Flexibility', 'To Improve Flexibility'), ('To Lower Cholesterol', 'To Lower Cholesterol'), ('To Improve Muscular Conditioning', 'To Improve Muscular Conditioning'), ('To Improve Nutrition Habits', 'To Improve Nutrition Habits'), ('To Reduce Lower Back Pain', 'To Reduce Lower Back Pain'), ('To Feel Better Overall', 'To Feel Better Overall'), ('To Gain Weight/Muscle', 'To Gain Weight/Muscle'), ('To Tone/Firm', 'To Tone/Firm'), ('To Increase Energy Level', 'To Increase Energy Level'), ('To Rehabilitate Injury', 'To Rehabilitate Injury')], max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
